org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.parallel=true

mod_id=efab
mod_name=EFab
mod_group_id=mcjty.efab
mod_version=0.3.3
mod_license=MIT
mod_authors=McJty, lyuxc_
mod_description=Extended crafting, power, fluid, and automation machines for Minecraft 1.21.1.

minecraft_version=1.21.1
neo_version=21.1.200
jei_version=19.21.2.313
top_version=1.21_neo-12.0.8-7
jade_version=7545219
crafttweaker_version=21.0.38
kubejs_version=2101.7.2-build.368

neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17
